#ifndef DRAW_H
#define DRAW_H

void drawHouse(int offsetX = 0, int offsetY = 0, float scaleX = 1.0f, float scaleY = 1.0f);
void drawBuilding(float x, float width, float height);
void drawPondInfrontOfSriti();
void drawStepsInFrontOfSritiShoudho();
void drawRiverAndLake();
void drawSun(float cx, float cy, float radius, int segments = 100);
void drawStalls(float offsetX, float offsetY);
void drawMoon(float cx, float cy, float radius);
void drawBoat(int offsetX, int offsetY, float scaleX, float scaleY, bool motion, bool sail = true);
void drawStreetLamp(float x1, float y1, float height);
void drawLine(float x1, float y1, float x2, float y2);
void drawFilledTriangle(float x1, float y1, float x2, float y2, float x3, float y3, float r, float g, float b);
void drawCircle(float cx, float cy, float r, float red, float green, float blue);
void drawMetroPillars();
void drawMemorial(int offsetX = 0, int offsetY = 0, float scaleX = 1.0f, float scaleY = 1.0f);
void drawCloudLarge(float x, float y, float scale = 1.0f);
void drawCloudMedium(float x, float y, float scale = 1.0f);
void drawCloudSmall(float x, float y, float scale = 1.0f);
void drawFlower(float cx, float cy);
void drawSritiShoudho();
void drawTree(float x, float y);
void drawCar(float x, float y);
void drawMountain(float x, float baseY, float width, float height, float r, float g, float b);
void drawFlag(float offsetX, float offsetY, float scale);
void drawMountain1(float x, float baseY, float width, float height, float r, float g, float b);
void drawMountain2(float x, float baseY, float width, float height, float r, float g, float b);
void drawMountain3(float x, float baseY, float width, float height, float r, float g, float b);
void drawTree(float x, float y, float scale);
void drawPalmTree(float x, float y, float scale);
void drawSmallTree2(float cx, float cy, float r, float g, float b, float scale);
void drawSmallTree1(float cx, float cy, float r, float g, float b, float sizeX, float sizeY);
void drawConcreteFloor();
void drawParkingLot(float offsetX, float offsetY);
void drawGrid(float spacing, int width, int height);
void drawBus(float x, float y, float scale, float angleDegrees);
void updateTrain(int value);
void drawMetro(int offsetX = 0, int offsetY = 0, float scaleX = 5.0f, float scaleY = 5.0f);
void updateTrain(int value);
void drawRoadWithLamps();
void drawMetroTrack();
void drawMainBuilding(int offsetX = 0, int offsetY = 0, float scaleX = 1.0f, float scaleY = 1.0f);
void drawMiniPlan(float offsetX = 0.0f, float offsetY = 0.0f, float scaleX = 1.0f, float scaleY = 1.0f);
void initRain(bool &rainActive);
void updateRain();
void drawRain(bool &rainActive);
void drawSnow(bool &snowActive);
void initSnowflakes();
void updateSnowflakes();
void drawFireParticles(bool &fireActive);
void initFireParticles();
void updateFireParticles(bool &fireActive);
void controlKeyboard(unsigned char key, bool &rainActive, bool &showMemorial, bool &isNight, bool &snowActive, bool &fireActive);
void drawBackground(int &GROUND_TOP_Y, bool &isNight, float &cloud1X, float &cloud2X, float &cloud3X);
void drawTreesRightSide();
void drawFlowersBeforeMemorial();
#endif
